#!/bin/bash

# shellcheck source=start-utils
. /image/scripts/start-utils

# some primitive tests
# $(( $(version_to_int "2.8.1" "55") > $(version_to_int "2.8.1" ) )) should be false
# $(( $(version_to_int "2.8.1" "55") > $(version_to_int "2.8" ) )) should be true
# $(( $(version_to_int "2.8.1" ) > $(version_to_int "2.8" ) )) should be true
# $(( $(version_to_int "2.9" ) > $(version_to_int "2.8.99" ) )) should be true
function version_to_int() {
    local major=$(echo "$1" | cut -d '.' -f1) # up to 99
    local minor=$(echo "$1" | cut -d '.' -f2) # up to 99
    local patch=$(echo "$1" | cut -d '.' -f3) # up to 99
    local daily="$2" # up to 9999

    major="$(( ${major:-00} * 100000000 ))"
    minor="$(( ${minor:-00} * 1000000 ))"
    patch="$(( ${patch:-00} * 10000 ))"
    daily="${daily:-9999}"

    echo $(( $major + $minor + $patch + $daily ))
}

function substitute_motd() {
    # for more details see: https://unix.stackexchange.com/a/648548

    local tmppath=$(mktemp)

    echo "${1}" \
    | sed 's/MODPACK_VERSION/'"${2}"'/' \
    | sed 's/DAILY_BUILD/'"${3}"'/' \
    > $tmppath
    local motd=$(cat $tmppath)

    rm -f $tmppath

    echo ${motd}
}

function create_backup() {
    cd /data

    if [[ -d World ]]; then
        local world_dir="World"
    elif [[ -d world ]]; then
        local world_dir="world"
    else
        local world_dir=""
    fi

    if [[ "${world_dir}" == "" ]]; then
        log "not creating backup as world folder doesn't exist"
    else
        local backup_file="docker-backups/${1}.zip"

        log "creating backup: ${backup_file}"

        mkdir -p docker-backups/new
        chown minecraft:minecraft docker-backups/new

        if [[ -f "${backup_file}" ]]; then
            log "deleting old backup"
            rm "${backup_file}"
        fi

        mkdir -p docker-backups/new/config
        chown minecraft:minecraft docker-backups/new/config

        cp -rp serverutilities visualprospecting ${world_dir} docker-backups/new/
        cp -rp config/JourneyMapServer docker-backups/new/config/
        cd docker-backups/new
        zip -rq "../../${backup_file}" .
        chown minecraft:minecraft "../../${backup_file}"
        cd ../..

        log "cleaning up"
        rm -rf docker-backups/new
    fi
}

# some primitive tests (assuming files exist: 209000312.zip 209000310.zip 209000301.zip 209000296.zip old.zip)
# $[[ "$(find_backup_file 209000320)" == "docker-backups/209000312.zip" ]] should be true
# $[[ "$(find_backup_file 209000310)" == "docker-backups/209000310.zip" ]] should be true
# $[[ "$(find_backup_file 209000309)" == "docker-backups/209000301.zip" ]] should be true
# $[[ "$(find_backup_file 209000301)" == "docker-backups/209000301.zip" ]] should be true
# $[[ "$(find_backup_file 209000300)" == "docker-backups/209000296.zip" ]] should be true
# $[[ "$(find_backup_file 209000296)" == "docker-backups/209000296.zip" ]] should be true
# $[[ "$(find_backup_file 209000295)" == "docker-backups/old.zip" ]] should be true
function find_backup_file() {
    cd /data

    if [[ -f "docker-backups/${1}.zip" ]]; then
        echo "docker-backups/${1}.zip"
        return 0
    fi

    mapfile -d '' BACKUPS < <(find docker-backups -name "*.zip" -printf "%f\0")

    # remove file extensions
    for i in "${!BACKUPS[@]}"; do
        BACKUPS[$i]=$(echo "${BACKUPS[$i]}" | cut -d "." -f1)
    done

    # sort in descending order
    IFS=$'\n' BACKUPS=($(sort -r <<<"${BACKUPS[*]}"))
    unset IFS

    # remove old.zip if it exists
    if [[ "${BACKUPS[0]}" == "old" ]]; then
        BACKUPS=(${BACKUPS[@]:1})
    fi

    # remove all newer backups
    while [[ ! ${#BACKUPS[@]} -eq 0 ]] && (( "${BACKUPS[0]}" > "${1}" )); do
        BACKUPS=(${BACKUPS[@]:1})
    done

    # if it's not empty
    if [[ ! ${#BACKUPS[@]} -eq 0 ]]; then
        echo "docker-backups/${BACKUPS[0]}.zip"
        unset BACKUPS
        return 0
    fi
    unset BACKUPS

    if [[ -f "docker-backups/old.zip" ]]; then
        echo "docker-backups/old.zip"
        return 0
    fi

    return 1
}

function load_backup() {
    cd /data

    local backup_file=$(find_backup_file "${1}")

    if [[ "$backup_file" == "" ]]; then
        log "ERR backup zip not found: docker-backups/${1}.zip"
        exit 1
    fi

    log "loading backup: ${backup_file}"

    mkdir -p docker-backups/new
    chown minecraft:minecraft docker-backups/new

    if [[ -d World ]]; then
        local world_dir="World"
    else
        local world_dir="world"
    fi

    rm -rf serverutilities visualprospecting ${world_dir} config/JourneyMapServer

    unzip -q $backup_file -d docker-backups/new
    chown -R minecraft:minecraft docker-backups/new
    # fix question mark permissions
    # https://unix.stackexchange.com/a/393603
    chmod -R a+X docker-backups/new
    mv docker-backups/new/serverutilities docker-backups/new/visualprospecting docker-backups/new/${world_dir} .
    mv docker-backups/new/config/JourneyMapServer ./config

    log "cleaning up"
    rm -rf docker-backups/new
}

function install_server() {
    cd /data

    if [[ ! -f /download/server.zip ]]; then
        log "ERR server.zip not found"
        exit 1
    fi

    log "installing server.zip"

    mkdir -p docker-backups/install && chown minecraft:minecraft docker-backups/install
    mkdir -p docker-backups/install/config && chown minecraft:minecraft docker-backups/install/config

    unzip -q /download/server.zip -d docker-backups/install/

    chown -R minecraft:minecraft docker-backups/install
    # fix question mark permissions
    # https://unix.stackexchange.com/a/393603
    chmod -R a+X docker-backups/install

    # persist JourneyMap id
    cp -rp config/JourneyMapServer docker-backups/install/config/

    rm -rf config libraries mods *.jar java9args.txt

    cd docker-backups/install
    mv config libraries mods *.jar java9args.txt ../..
    if [[ ! -d ../../serverutilities ]]; then
        mv serverutilities ../..
    fi
    mv -n server-icon.png ../..

    cd ../..

    log "cleaning up"
    rm -rf docker-backups/install
}

function install_additional_mods() {
    cd /data

    if [[ -d /mods ]]; then
        log "copying additional mods"

        cp -rp /mods/* mods/
    fi

    if [[ $(find ./mods -maxdepth 1 -name 'gtnh-web-map-*.jar' -printf 1 -quit) ]]; then
        log "removing existing web map jar file"
        rm -f mods/gtnh-web-map-*.jar
    fi

    if [[ ${1} != "" ]]; then
        log "installing gtnh web map"
        mv /download/gtnh-web-map-*.jar mods/
    fi
}
