name: Test image

on: 
  workflow_call:
    inputs:
      gtnh-version:
        type: string
        required: true
      nightly-version:
        type: string
        required: false

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Set up pipx
        run: |
          apt install pipx
          pipx ensurepath
      - name: install mcstatus
        run: |
          pipx install mcstatus==11.1.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/image.tar
      - name: Create server container
        run: |
          docker create -v ./server:/data --name minecraft-gtnh3 -p 25565:25565 -e MEMORY=8G -e MOTD='GT New Horizons ${MODPACK_VERSION}-nightly${GTNH_NIGHTLY_BUILD}' -e EULA=TRUE ${{ env.IMAGE_NAME }}:latest
          | echo "CONTAINER_ID=`echo $(cat -)`" >>${GITHUB_ENV}
      - name: Start server container
        run: |
          docker start ${{ env.CONTAINER_ID }}
      - name: Wait for server to start
        run: |
          declare -i c=300 \
          && while (( $(c) > 0 )); do
            mcstatus 127.0.0.1 ping && break
            (( c -= 1 ))
          done
          if (( c == 0 )); then
            exit 1
          fi
      - name: Read MOTD
        run: |
          mcstatus 127.0.0.1 status \
          | grep -oP "(?<=raw\=\').+(?=\', bedrock=False)"
          | echo "MOTD=`echo $(cat -)`" >>${GITHUB_ENV}
      - name: Check MOTD GTNH version
        if: false
        run: |
          echo ${{ env.MOTD }} \
          | grep -oP "(?<=GT New Horizons ).+(?=-)" \
          | [[ $(cat -) == ${{ inputs.gtnh-version }} ]]
      - name: Check MOTD nightly version
        run: |
          echo ${{ env.MOTD }} \
          | grep -oP "(?<=-nightly).+$" \
          | [[ $(cat -) == ${{ inputs.nightly-version }} ]]
      - name: Stop and delete server container
        run: |
          docker rm -f ${{ env.CONTAINER_ID }}
