name: Release tagged image

on: 
  workflow_call:
    inputs:
      gtnh-version:
        type: string
        required: true
      nightly-version:
        type: string
        required: false

defaults:
  run:
    shell: bash

jobs:
  push:
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Download cached docker image
      run: |
        curl --fail-with-body -X GET http://192.168.0.145:25000/attachments/gtnh-server/1/image.tar -o /tmp/image.tar
    - name: Load image
      run: |
        docker load --input /tmp/image.tar
    - name: Push normal
      if: inputs.nightly-version == -1
      run: |
        docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.IMAGE_NAME }}:${{ inputs.gtnh-version }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:${{ inputs.gtnh-version }}
        docker tag ghcr.io/${{ env.IMAGE_NAME }}:${{ inputs.gtnh-version }} ghcr.io/${{ env.IMAGE_NAME }}:stable
        docker push ghcr.io/${{ env.IMAGE_NAME }}:stable
    - name: Push nightly
      if: inputs.nightly-version != -1
      run: |
        docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.IMAGE_NAME }}:nightly-${{ inputs.nightly-version }}
        docker push ghcr.io/${{ env.IMAGE_NAME }}:nightly-${{ inputs.nightly-version }}
        docker tag ghcr.io/${{ env.IMAGE_NAME }}:nightly-${{ inputs.nightly-version }} ghcr.io/${{ env.IMAGE_NAME }}:nightly
        docker push ghcr.io/${{ env.IMAGE_NAME }}:nightly
    - name: Remove local image
      if: always()
      run: |
        docker image rm ${{ env.IMAGE_NAME }}
    - name: Remove cached docker image
      if: always()
      run: |
        curl --fail-with-body -X DELETE http://192.168.0.145:25000/attachments/gtnh-server/1/image.tar
