name: Check for new nightly release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # 3:00am UTC every day
    
jobs:
  check:
    runs-on: [self-hosted, linux]
    outputs:
      gtnh_version: ${{ steps.fetch-version.outputs.vers }}
      nightly_version: ${{ steps.fetch-nightly.outputs.vers }}
    steps:
    - id: fetch-version
      name: get latest gtnh version (TODO; actually return version read from github tags page)
      run: |
        echo "2.7.2" \
        | echo "vers=$(cat -)" >> "$GITHUB_OUTPUT"
    - id: fetch-nightly
      name: get latest nightly version number
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/GTNewHorizons/DreamAssemblerXXL/actions/runs?per_page=1 \
        | jq -r ".workflow_runs[0].run_number" \
        | echo "vers=$(cat -)" >> "$GITHUB_OUTPUT"

  build:
    needs: [check]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/define-build-and-test.yml
    with:
      gtnh-version: ${{ needs.check.outputs.gtnh_version }}
      nightly-version: ${{ needs.check.outputs.nightly_version }}
    secrets: inherit
