name: Check for new nightly release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # 4:00am UTC every day

jobs:
  check:
    runs-on: [self-hosted, linux]
    outputs:
      gtnh_version: ${{ steps.fetch-version.outputs.vers }}
      nightly_version: ${{ steps.fetch-nightly.outputs.vers }}
    steps:
    - name: check if latest nightly build failed
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/GTNewHorizons/DreamAssemblerXXL/actions/workflows/58547244/runs?per_page=1 \
        | jq -r ".workflow_runs[0] | .conclusion" \
        | [[ $(cat -) != "success" ]] \
        && echo "latest nightly build didn't succeed, exiting..." \
        && exit 1
        || echo "latest nightly build succeeded"
    - id: fetch-version
      name: get latest gtnh version
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/GTNewHorizons/GT-New-Horizons-Modpack/tags?per_page=100 \
        | jq -r ".[] | .name" \
        | grep -oP "^\d+\.\d+\.\d+$" \
        | head -n 1 \
        | echo "vers=$(cat -)" >> "$GITHUB_OUTPUT"
    - id: fetch-nightly
      name: get latest nightly version number
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/GTNewHorizons/DreamAssemblerXXL/actions/workflows/58547244/runs?per_page=1 \
        | jq -r ".workflow_runs[0] | .run_number" \
        | echo "vers=$(cat -)" >> "$GITHUB_OUTPUT"
    - name: print modpack version number
      run: |
        echo "Found modpack version ${{ steps.fetch-version.outputs.vers }}"
    - name: print latest nightly version number
      run: |
        echo "Found latest nightly version ${{ steps.fetch-nightly.outputs.vers }}"

  build:
    needs: [check]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/define-build-and-test.yml
    with:
      gtnh-version: ${{ needs.check.outputs.gtnh_version }}
      nightly-version: ${{ needs.check.outputs.nightly_version }}
    secrets: inherit
